Add collision avoidance test
frc3512/Robot-2020 pull request #112
Opened 2020-12-13 02:06 UTC by LambdaByte0707

The test ensures that the turret moves out of the way when the trigger is pressed and that
the climber is able to move once the turret is confirmed to be out of the way.

Fixes #101

2020-12-13 17:51 UTC, calcmogul requested changes
Could you add some comments describing what the test is trying to do at each step? I don't think this test is actually testing anything because it doesn't give the climber or turret time to move anywhere and actually try to conflict with each other.

2020-12-13 17:51 UTC, calcmogul commented on src/test/cpp/CollisionAvoidanceTest.cpp
> +    appendageStick1.SetTrigger(true);
```suggestion
    appendageStick1.SetRawButton(1, true);
```
This function is in `JoystickSim`'s `GenericHIDSim` base class.

2020-12-17 04:28 UTC, LambdaByte0707 commented
UPDATE: Currently the test fails as of writing (12/16/20). There are some issues that I need to still iron out, but I overall redid the test design than what I previous did in my first push to the PR. Plan to continue to work on it, but due to the holidays coming up, its uncertain when I'll complete it by.

*Sorry if this seems unnecessary, but its a way of remembering what was accomplished to serve as a reminder, especially during the holidays :)*

2021-01-09 01:39 UTC, calcmogul commented
I think this test is missing a few steps. It should be doing the following in order:

* Try moving climber and verify turret moves out of the way (the turret starts at 0 radians and the climber starts at the bottom)
* Ensure climber can now move up into turret's way
* Ensure turret can't move into climber
* Move climber down
* Ensure turret can move full range again

2021-01-09 01:42 UTC, calcmogul requested changes

2021-01-09 01:42 UTC, calcmogul commented on src/test/cpp/CollisionAvoidanceTest.cpp
> +    // of the climber)
The climber moving in the way of the climber makes no sense.

2021-01-09 01:42 UTC, calcmogul commented on src/test/cpp/CollisionAvoidanceTest.cpp
> +    frc::sim::StepTiming(20_ms);
This doesn't wait until the turret is finished moving. 20ms is certainly not enough time. Use a while loop here.

2021-08-05 02:24 UTC, merged